# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
    body_listener: true
    format_listener:
        rules:
           - {path: '^/api', priorities: ['json'], fallback_format: json}
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    param_fetcher_listener: true  
    view:
        view_response_listener: 'force'
        formats: 
            json: true
